### ISSUE TITLE
Documentation lacks sufficient setup information to prevent missing class error.

### ISSUE THREAD

**Issue by garretwilson** [Pante/elementary#294]
I'm using Java 21 to compile a Maven project that uses Java 17. After working around #293, I started trying to create a bare-bones test that does nothing except print things so I can get an idea of what is going on.

Ultimately I just need access to an `Element` for a method so I can make sure my library finds the right annotations on the method.

Inside Eclipse 2023-12 I created a unit test `MyTest` in `src/test/java/com/example/MyTest.java` (the expected location in Maven for unit tests). I started out with the most basic possible:

```java
@ExtendWith(ToolsExtension.class)
@Introspect
public class MyTest {

  @Test
  void test() {
  }
}
```

Trying to run this, both in inside Eclipse and from Maven on the command line, gives:

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [com.karuslabs.elementary.junit.ToolsExtension] failed to instantiate test class [com.example.MyTest]: "com/example/MyTest.java" does not exist on the current classpath
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalArgumentException: "com/example/MyTest.java" does not exist on the current classpath
	at com.karuslabs.elementary.file.FileObjects.ofResource(FileObjects.java:157)
	at com.karuslabs.elementary.file.FileObjects.ofClass(FileObjects.java:140)
	at com.karuslabs.elementary.file.FileObjects.scan(FileObjects.java:60)
	at com.karuslabs.elementary.junit.DaemonCompiler.of(DaemonCompiler.java:66)
	at com.karuslabs.elementary.junit.Daemon.initialize(Daemon.java:91)
	at com.karuslabs.elementary.junit.Daemon.createTestInstance(Daemon.java:68)
	at com.karuslabs.elementary.junit.ToolsExtension.createTestInstance(ToolsExtension.java:54)
	... 3 more
```

My guess is that it's looking for the source code of `MyTest` and can't find it—but I can't imagine why, as it's in the standard location for unit tests.

I removed `@Introspect` and it crashed spectacularly:

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [com.karuslabs.elementary.junit.ToolsExtension] failed to instantiate test class [com.example.MyTest]: com.karuslabs.elementary.CompilationException: javac either crashed or failed to start.
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.util.concurrent.CompletionException: com.karuslabs.elementary.CompilationException: javac either crashed or failed to start.
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.karuslabs.elementary.junit.DaemonCompiler.environment(DaemonCompiler.java:114)
	at com.karuslabs.elementary.junit.Daemon.initialize(Daemon.java:97)
	at com.karuslabs.elementary.junit.Daemon.createTestInstance(Daemon.java:68)
	at com.karuslabs.elementary.junit.ToolsExtension.createTestInstance(ToolsExtension.java:54)
	... 3 more
Caused by: com.karuslabs.elementary.CompilationException: javac either crashed or failed to start.
	at com.karuslabs.elementary.junit.DaemonCompiler.run(DaemonCompiler.java:99)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/karuslabs/utilitary/type/TypeMirrors
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:168)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at com.karuslabs.elementary.Compiler.compile(Compiler.java:98)
	at com.karuslabs.elementary.junit.DaemonCompiler.run(DaemonCompiler.java:96)
Caused by: java.lang.NoClassDefFoundError: com/karuslabs/utilitary/type/TypeMirrors
	at com.karuslabs.elementary.junit.DaemonCompiler$Environment.<init>(DaemonCompiler.java:187)
	at com.karuslabs.elementary.junit.DaemonCompiler$DaemonProcessor.process(DaemonCompiler.java:148)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.karuslabs.utilitary.type.TypeMirrors
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
```

I hope I'm missing something simple. This library seemed to have so much potential.

**Comment by garretwilson** [comment]
OK, good news; I'm making progress. It turns out there is a [separate documentation page](https://github.com/Pante/elementary/blob/master/docs/elementary/configuring-%40Introspect.md) indicating that I must configure my project to _copy all the unit test source files_ to the `test-classes` target (output) directory so that Elementary can find them.

I understand Elementary requires this, but it wasn't clear from the documentation that this step was required. (A new user doesn't automatically know the mechanism Elementary uses to find and compile the source code.)

As noted in #295, it will break unless Utilitary is added as a dependency. (As I mentioned elsewhere it's unclear to me why Elementary doesn't include this dependency transitively already.)

I would recommend that as part of the documentation you have a "getting started" section that provides a list of everything needed to use Elementary, including 1) adding the additional JUnit dependency (#293), 2) including Utilitary (#295), and updating the project to copy source files. The current [home page](https://github.com/Pante/elementary) and the [tour](https://github.com/Pante/elementary/blob/master/docs/elementary/tour.md) make it seem like I can just add a dependency to JUnit and to Utilitary and I'm good to go, but as this ticket shows, further steps need to be performed.

**Comment by garretwilson** [comment]
I have this working for my initial use case, and so far it is very nice and does just what I needed! Thus I think the issue here is simply insufficient and misleading documentation.

**Comment by Pante** [comment]
Thanks for the detailed issue, I've updated the documentation & will release `2.0.1` to address the missing dependency issue.

**Comment by garretwilson** [comment]
Thanks for being attentive to my feedback and for quickly making changes. I've tried out the new v2.0.1 and it seems to be working well. I've just started using the library, but so far it seems to bring exactly what I needed to my unit tests. This will be really helpful.

**Comment by Pante** [comment]
Forgot to close this issue, whoops.
